version: '3'
services:

  kafka:
    build:
     context: dockerfiles
     dockerfile: Dockerfile
    image: mvilche/apache-kafka:2.3.0-alpine3.9
    environment:
     - ZOOKEEPER_PORT=2181
     - ZOOKEEPER_HOST=zookeeper
    networks:
     - integracion

  zookeeper:
    image: mvilche/apache-zookeeper:3.5.5-alpine3.9
    networks:
     - integracion



networks:
  integracion:
